name: Update package.json

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: GitHub Action for package.json update.
      uses: taichi/actions-package-update@v0.5.0
      env:
        AUTHOR_EMAIL: ritayanout@gmail.com
        AUTHOR_NAME: Ritayan Chakraborty
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: debug
      with:
        args: -u --packageFile package.json --loglevel verbose
